// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThesesApi.Data;

#nullable disable

namespace ThesesApi.Data.Migrations
{
    [DbContext(typeof(ThesisContext))]
    partial class ThesisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("ThesesApi.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Workplace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("ThesesApi.Models.Thesis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<long>("MainAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MainAuthorId");

                    b.ToTable("thesis");
                });

            modelBuilder.Entity("ThesesApi.Models.ThesisOtherAuthors", b =>
                {
                    b.Property<long>("ThesisId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ThesisId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("otherAuthors");
                });

            modelBuilder.Entity("ThesesApi.Models.Thesis", b =>
                {
                    b.HasOne("ThesesApi.Models.Person", "MainAuthor")
                        .WithMany()
                        .HasForeignKey("MainAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MainAuthor");
                });

            modelBuilder.Entity("ThesesApi.Models.ThesisOtherAuthors", b =>
                {
                    b.HasOne("ThesesApi.Models.Person", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThesesApi.Models.Thesis", "Thesis")
                        .WithMany("OtherAuthors")
                        .HasForeignKey("ThesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Thesis");
                });

            modelBuilder.Entity("ThesesApi.Models.Thesis", b =>
                {
                    b.Navigation("OtherAuthors");
                });
#pragma warning restore 612, 618
        }
    }
}
